//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcment
    {
        public long AnnId { get; set; }
        public Nullable<long> PSId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Upload { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsVisibleToBothSessions { get; set; }
    
        public virtual ProjectSession ProjectSession { get; set; }
        public virtual User User { get; set; }
    }
}
