//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignExternalProject
    {
        public int AssignexternalProjectId { get; set; }
        public long ExtGroupID { get; set; }
        public long ProjectId { get; set; }
        public long ProjectSessionId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectSession ProjectSession { get; set; }
    }
}
