//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    
    public partial class AuthenticateUser
    {
        public long UId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string OfficePhone { get; set; }
        public string MobileNumber { get; set; }
        public short RoleId { get; set; }
        public int DepartmentId { get; set; }
        public bool Status { get; set; }
        public Nullable<short> Rid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<long> PGId { get; set; }
        public Nullable<long> StudentId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
