//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public long COMId { get; set; }
        public long Message_From { get; set; }
        public long Message_To { get; set; }
        public string EmailSubject { get; set; }
        public string Message_Content { get; set; }
        public bool ReadStatus { get; set; }
        public Nullable<long> ParentId { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public Nullable<bool> Replied { get; set; }
        public Nullable<long> Project_Id { get; set; }
        public string File_Attached { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
