//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalGroup
    {
        public long EGId { get; set; }
        public Nullable<long> Ext_User1 { get; set; }
        public Nullable<long> Ext_User2 { get; set; }
        public Nullable<long> Ext_user3 { get; set; }
        public Nullable<long> ProjectSessionId { get; set; }
        public Nullable<long> ProjectId { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ProjectSession ProjectSession { get; set; }
        public virtual Project Project { get; set; }
    }
}
