//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PresentationSchedule
    {
        public long PRSCId { get; set; }
        public long ProjectId { get; set; }
        public System.TimeSpan TimeFrom { get; set; }
        public System.TimeSpan TimeTo { get; set; }
        public System.DateTime PresentationDate { get; set; }
        public long PSId { get; set; }
        public long PMSId { get; set; }
        public int RoomNumber { get; set; }
        public Nullable<long> Evaluator1 { get; set; }
        public Nullable<long> Evaluator2 { get; set; }
        public Nullable<long> Evaluator3 { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectMileStone ProjectMileStone { get; set; }
        public virtual ProjectSession ProjectSession { get; set; }
        public virtual RoomsForPresentation RoomsForPresentation { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
