//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectGroup
    {
        public long PGId { get; set; }
        public long StudentId { get; set; }
        public long ProjectId { get; set; }
        public Nullable<long> StudentID2 { get; set; }
        public Nullable<long> StudentID3 { get; set; }
        public Nullable<long> StudentID4 { get; set; }
        public Nullable<long> StudentID5 { get; set; }
        public Nullable<long> ExtGroupID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
