//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMileStoneDeadLine
    {
        public long PMSDId { get; set; }
        public long PMSId { get; set; }
        public System.DateTime DeadLine { get; set; }
        public long PSId { get; set; }
        public string Description { get; set; }
        public System.TimeSpan TimeSpan { get; set; }
    
        public virtual ProjectMileStone ProjectMileStone { get; set; }
        public virtual ProjectSession ProjectSession { get; set; }
    }
}
