//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.ProjectGroups = new HashSet<ProjectGroup>();
            this.UploadedMileStones = new HashSet<UploadedMileStone>();
            this.SupervisodBies = new HashSet<SupervisodBy>();
            this.WeeklyMeetings = new HashSet<WeeklyMeeting>();
            this.PresentationSchedules = new HashSet<PresentationSchedule>();
            this.ScheduleFacultyStudents = new HashSet<ScheduleFacultyStudent>();
            this.ProjectDirectories = new HashSet<ProjectDirectory>();
            this.Communications = new HashSet<Communication>();
            this.AssignExternalProjects = new HashSet<AssignExternalProject>();
            this.ExternalGroups = new HashSet<ExternalGroup>();
            this.MileStoneEvaluations = new HashSet<MileStoneEvaluation>();
        }
    
        public long PId { get; set; }
        public string Tiltle { get; set; }
        public string Description { get; set; }
        public string UploadedFile { get; set; }
        public long UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public short Status { get; set; }
        public Nullable<long> StudentId { get; set; }
        public long ProjectSessionId { get; set; }
        public Nullable<long> ProposedBy { get; set; }
        public string KeyFeatures { get; set; }
        public Nullable<short> Complexity { get; set; }
        public string EffortsRequired { get; set; }
        public string Domain { get; set; }
        public string RequiredToolsAndTech { get; set; }
        public string SpecialCharactersRequired { get; set; }
        public Nullable<int> researchGroupId { get; set; }
        public Nullable<long> ExtGroupID { get; set; }
    
        public virtual ProjectSession ProjectSession { get; set; }
        public virtual ResearchGroup ResearchGroup { get; set; }
        public virtual ICollection<ProjectGroup> ProjectGroups { get; set; }
        public virtual ICollection<UploadedMileStone> UploadedMileStones { get; set; }
        public virtual ICollection<SupervisodBy> SupervisodBies { get; set; }
        public virtual ICollection<WeeklyMeeting> WeeklyMeetings { get; set; }
        public virtual ICollection<PresentationSchedule> PresentationSchedules { get; set; }
        public virtual ICollection<ScheduleFacultyStudent> ScheduleFacultyStudents { get; set; }
        public virtual ICollection<ProjectDirectory> ProjectDirectories { get; set; }
        public virtual ICollection<Communication> Communications { get; set; }
        public virtual ICollection<AssignExternalProject> AssignExternalProjects { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<ExternalGroup> ExternalGroups { get; set; }
        public virtual ICollection<MileStoneEvaluation> MileStoneEvaluations { get; set; }
    }
}
