//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMileStone
    {
        public ProjectMileStone()
        {
            this.ProjectMileStoneDeadLines = new HashSet<ProjectMileStoneDeadLine>();
            this.UploadedMileStones = new HashSet<UploadedMileStone>();
            this.PresentationSchedules = new HashSet<PresentationSchedule>();
            this.MileStoneEvaluations = new HashSet<MileStoneEvaluation>();
        }
    
        public long PMSId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> MileStoneMarks { get; set; }
    
        public virtual ICollection<ProjectMileStoneDeadLine> ProjectMileStoneDeadLines { get; set; }
        public virtual ICollection<UploadedMileStone> UploadedMileStones { get; set; }
        public virtual ICollection<PresentationSchedule> PresentationSchedules { get; set; }
        public virtual ICollection<MileStoneEvaluation> MileStoneEvaluations { get; set; }
    }
}
