//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSession
    {
        public ProjectSession()
        {
            this.Announcments = new HashSet<Announcment>();
            this.Projects = new HashSet<Project>();
            this.ProjectMileStoneDeadLines = new HashSet<ProjectMileStoneDeadLine>();
            this.PresentationSchedules = new HashSet<PresentationSchedule>();
            this.TemplateDocuments = new HashSet<TemplateDocument>();
            this.ProjectDirectories = new HashSet<ProjectDirectory>();
            this.AssignExternalProjects = new HashSet<AssignExternalProject>();
            this.Users = new HashSet<User>();
            this.ExternalGroups = new HashSet<ExternalGroup>();
        }
    
        public long PSId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> Year { get; set; }
    
        public virtual ICollection<Announcment> Announcments { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<ProjectMileStoneDeadLine> ProjectMileStoneDeadLines { get; set; }
        public virtual ICollection<PresentationSchedule> PresentationSchedules { get; set; }
        public virtual ICollection<TemplateDocument> TemplateDocuments { get; set; }
        public virtual ICollection<ProjectDirectory> ProjectDirectories { get; set; }
        public virtual ICollection<AssignExternalProject> AssignExternalProjects { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<ExternalGroup> ExternalGroups { get; set; }
    }
}
