//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsForPresentation
    {
        public RoomsForPresentation()
        {
            this.PresentationSchedules = new HashSet<PresentationSchedule>();
        }
    
        public int RoomId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<PresentationSchedule> PresentationSchedules { get; set; }
    }
}
