//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleFacultyStudent
    {
        public long ScheduleId { get; set; }
        public Nullable<bool> isStudent { get; set; }
        public Nullable<bool> isFaculty { get; set; }
        public Nullable<int> TSId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Day { get; set; }
    
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
