//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisodBy
    {
        public long SId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> SupervisodBy1 { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
