//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateDocument
    {
        public int TDId { get; set; }
        public string Title { get; set; }
        public string UploadedFile { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public Nullable<long> PSId { get; set; }
    
        public virtual ProjectSession ProjectSession { get; set; }
    }
}
