//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedMileStone
    {
        public UploadedMileStone()
        {
            this.UploadedMileStoneDocs = new HashSet<UploadedMileStoneDoc>();
            this.UploadedMileStoneDocs1 = new HashSet<UploadedMileStoneDoc>();
            this.UploadedMileStoneDocsVersions = new HashSet<UploadedMileStoneDocsVersion>();
        }
    
        public long UMSId { get; set; }
        public long PMSId { get; set; }
        public long ProjectId { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public string UploadedFile { get; set; }
        public Nullable<long> UploadedBy { get; set; }
        public long SupervisorId { get; set; }
        public string CommentBySupervisor { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ProjectMileStone ProjectMileStone { get; set; }
        public virtual ICollection<UploadedMileStoneDoc> UploadedMileStoneDocs { get; set; }
        public virtual ICollection<UploadedMileStoneDoc> UploadedMileStoneDocs1 { get; set; }
        public virtual ICollection<UploadedMileStoneDocsVersion> UploadedMileStoneDocsVersions { get; set; }
        public virtual User User { get; set; }
    }
}
