//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedMileStoneDocsVersion
    {
        public long UMSDVId { get; set; }
        public Nullable<long> UMSId { get; set; }
        public string UploadedFile { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<long> UploadedBy { get; set; }
    
        public virtual UploadedMileStone UploadedMileStone { get; set; }
    }
}
