//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Announcments = new HashSet<Announcment>();
            this.Communications = new HashSet<Communication>();
            this.Communications1 = new HashSet<Communication>();
            this.Communications2 = new HashSet<Communication>();
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.ProjectGroups = new HashSet<ProjectGroup>();
            this.Roles = new HashSet<Role>();
            this.ScheduleFacultyStudents = new HashSet<ScheduleFacultyStudent>();
            this.SupervisodBies = new HashSet<SupervisodBy>();
            this.UploadedMileStones = new HashSet<UploadedMileStone>();
            this.UploadedMileStoneDocs = new HashSet<UploadedMileStoneDoc>();
            this.ExternalGroups = new HashSet<ExternalGroup>();
            this.ExternalGroups1 = new HashSet<ExternalGroup>();
            this.ExternalGroups2 = new HashSet<ExternalGroup>();
            this.PresentationSchedules = new HashSet<PresentationSchedule>();
            this.PresentationSchedules1 = new HashSet<PresentationSchedule>();
            this.PresentationSchedules2 = new HashSet<PresentationSchedule>();
            this.MileStoneEvaluations = new HashSet<MileStoneEvaluation>();
            this.MileStoneEvaluations1 = new HashSet<MileStoneEvaluation>();
        }
    
        public long UId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string CiitExtension { get; set; }
        public string MobileNumber { get; set; }
        public short RoleId { get; set; }
        public int DepartmentId { get; set; }
        public bool Status { get; set; }
        public string RegistrationNo { get; set; }
        public string Designation { get; set; }
        public Nullable<double> Cgpa { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<int> ResearchId { get; set; }
        public string UploadImage { get; set; }
        public Nullable<long> ProjectSessionId { get; set; }
        public Nullable<long> EntityRecordID { get; set; }
        public string E_Specialization { get; set; }
        public string E_CNIC { get; set; }
        public string E_ContactAddresss { get; set; }
        public string E_Office { get; set; }
        public Nullable<bool> IsGrouped { get; set; }
    
        public virtual ICollection<Announcment> Announcments { get; set; }
        public virtual ICollection<Communication> Communications { get; set; }
        public virtual ICollection<Communication> Communications1 { get; set; }
        public virtual ICollection<Communication> Communications2 { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual ICollection<ProjectGroup> ProjectGroups { get; set; }
        public virtual ProjectSession ProjectSession { get; set; }
        public virtual ResearchGroup ResearchGroup { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<ScheduleFacultyStudent> ScheduleFacultyStudents { get; set; }
        public virtual ICollection<SupervisodBy> SupervisodBies { get; set; }
        public virtual ICollection<UploadedMileStone> UploadedMileStones { get; set; }
        public virtual ICollection<UploadedMileStoneDoc> UploadedMileStoneDocs { get; set; }
        public virtual ICollection<ExternalGroup> ExternalGroups { get; set; }
        public virtual ICollection<ExternalGroup> ExternalGroups1 { get; set; }
        public virtual ICollection<ExternalGroup> ExternalGroups2 { get; set; }
        public virtual ICollection<PresentationSchedule> PresentationSchedules { get; set; }
        public virtual ICollection<PresentationSchedule> PresentationSchedules1 { get; set; }
        public virtual ICollection<PresentationSchedule> PresentationSchedules2 { get; set; }
        public virtual ICollection<MileStoneEvaluation> MileStoneEvaluations { get; set; }
        public virtual ICollection<MileStoneEvaluation> MileStoneEvaluations1 { get; set; }
    }
}
