//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyMeeting
    {
        public long MId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string CommentBySupervisor { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
